name: LINE Bot Test

on:
  workflow_dispatch:

jobs:
  send-line:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to LINE
        run: |
          TOKEN="${{ secrets.LINE_TOKEN }}"
          USER_ID="U7a45281dfbd27d2caa942c62f29be03e"

          echo "Sending..."

          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d "{
            \"to\": \"$USER_ID\",
            \"messages\": [
              {
                \"type\": \"text\",
                \"text\": \"✅ TEST: ส่งจาก GitHub สำเร็จ!\"
              }
            ]
          }"

          echo "Done"
